apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Minikube typically provides a default StorageClass named "standard".
  - target:
      kind: PersistentVolumeClaim
      name: postgres-data
      namespace: genai-platform
    patch: |-
      - op: add
        path: /spec/storageClassName
        value: standard
