from typing import TypedDict


class WorkflowState(TypedDict, total=False):
    # Input
    request_text: str

    # Generated by the workflow
    incident_summary: str
    jira_title: str
    jira_description: str

    # Simple in-memory audit log of the steps taken
    logs: list[str]
