apiVersion: v1
kind: Service
metadata:
  name: genai-app
  namespace: genai-platform
spec:
  type: ClusterIP
  selector:
    app: genai-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
